import Foundation

/// Loads the bundled, build-time catalogue snapshot (`OfflineCatalogSnapshot.json`, generated by
/// `Scripts/generate_offline_catalog_snapshot.py` from Rebrickable's public `sets.csv` dump — see
/// that script before regenerating) so basic set identification (name/year/parts/image) still
/// resolves with no network at all, for the "scanning in a store with bad reception" case. Only
/// static catalogue facts are snapshotted — collection status and prices are deliberately NOT part
/// of this file and stay live-only, same as everywhere else in the app (see AGENTS.md).
///
/// `@unchecked Sendable` because `setsByNum` is populated once in `init` and never mutated again.
final class OfflineCatalogStore: @unchecked Sendable {
    static let shared = OfflineCatalogStore()

    private let setsByNum: [String: LegoSet]

    init(resourceName: String = "OfflineCatalogSnapshot", bundle: Bundle = .main) {
        guard
            let url = bundle.url(forResource: resourceName, withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let sets = try? JSONDecoder().decode([LegoSet].self, from: data)
        else {
            setsByNum = [:]
            return
        }
        setsByNum = Dictionary(uniqueKeysWithValues: sets.map { ($0.setNum, $0) })
    }

    /// Mirrors `RebrickableRepository.resolveSet`'s two-suffix lookup order: most set numbers
    /// encountered while scanning omit the "-1" variant suffix that Rebrickable's catalogue
    /// actually keys on, so the exact variant is tried first.
    func lookup(setNum: String) -> LegoSet? {
        setsByNum["\(setNum)-1"] ?? setsByNum[setNum]
    }

    var isEmpty: Bool { setsByNum.isEmpty }
}
